[package]
name = "simple-metrics"
version = "0.1.0"
edition = "2021"

authors = ["Sergei Mishin"]

description = "Library to flexibly render Prometheus metrics"
repository = "https://github.com/qezz/simple-metrics"
license = "MIT OR Apache-2.0"

keywords = ["metrics", "telemetry", "prometheus"]

[dependencies]
lazy_static = "1.5.0"
regex = "1.10.5"

[dev-dependencies]
criterion = "0.5"
regex = "1"
lazy_static = "1.5"

[[bench]]
name = "label_checker"
harness = false
